// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.amp.fbuservisual.model;

import com.amp.fbuservisual.model.FriendshipPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FriendshipPK_Roo_Configurable {
    
    declare @type: FriendshipPK: @Configurable;
    
}
