// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.amp.fbuservisual.model;

import com.amp.fbuservisual.model.FriendshipPK;
import java.io.Serializable;

privileged aspect FriendshipPK_Roo_Serializable {
    
    declare parents: FriendshipPK implements Serializable;
    
    private static final long FriendshipPK.serialVersionUID = 1L;
    
}
