// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.amp.fbuservisual.model;

import com.amp.fbuservisual.model.LikesPK;
import java.io.Serializable;

privileged aspect LikesPK_Roo_Serializable {
    
    declare parents: LikesPK implements Serializable;
    
    private static final long LikesPK.serialVersionUID = 1L;
    
}
