// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.amp.fbuservisual.model;

import com.amp.fbuservisual.model.UsersPK;
import java.io.Serializable;

privileged aspect UsersPK_Roo_Serializable {
    
    declare parents: UsersPK implements Serializable;
    
    private static final long UsersPK.serialVersionUID = 1L;
    
}
